### ISSUE TITLE
release130 分支编译问题

### ISSUE THREAD

**Issue by shengmingyue** [dolphindb/api-python-cpp#1]
Host OS 为 CentOS 8, 按照以下流程操作 :
1. [root@localhost /opt]# git clone   -b release130   https://github.com/dolphindb/api-python-cpp.git
2. [root@localhost /opt]# cd api-python-cpp/
3. [root@localhost /opt/api-python-cpp]# docker build -t dev-ssl .
4.  [root@localhost /opt/api-python-cpp]# chmod a+x    build.sh build-wheels.sh
5.  [root@localhost /opt/api-python-cpp]# ./build.sh
此时 出现 错误
gmake[2]: *** No rule to make target `../../pickleAPI/bin/linux_x64/python3.6/libDolphinDBAPI.a', needed by `../lib.linux-x86_64-3.6/dolphindb/dolphindbcpp.cpython-36m-x86_64-linux-gnu.so'.  Stop.
提示 关于 libDolphinDBAPI.a 的 错误.

又看了看 master 分支的代码 和 https://github.com/dolphindb/api-python-cpp/tree/release130/src/dolphindb)/binding.cpp 代码, 
感觉 对于 release130 分支 的 代码 来说, 
应该 在 pickleAPI 文件夹 下 存在 src 文件夹 和 CMakeLists.txt, 用来 编译 libDolphinDBAPI.a,
不知 是否 正确, 麻烦解答一下, 不胜感谢!

**Comment by tradercjz** [comment]
目前库里更新了一个PickleAPI的子目录，可以再看下有没有问题的。

**Comment by shengmingyue** [comment]
使用今天的 Commit, 可以编译通过了.
谢谢!
